name: letschat
description: A simple group chat application using flutter.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  page_transition: ^2.0.2
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.2
  flutter_icons: ^1.1.0
  smart_select: ^4.3.2
  convex_bottom_bar: ^2.6.0
#  google_maps_flutter: ^2.0.6
  firebase_database: ^7.1.1
  image_picker: ^0.7.5+2

  firebase_storage: ^8.1.3
  cloud_functions: ^1.1.2
  permission_handler: ^8.1.2
  camera: ^0.8.1+3
  shared_preferences: ^0.5.4+1
  path_provider: ^2.0.2
  file_picker: ^3.0.1
  path: 1.8.0
  video_player: ^2.1.10
#  flutter_svg: ^0.19.3
#  audio_picker: ^1.0.0
#  audioplayers: ^0.19.1
  giphy_picker: ^2.0.0
  speech_to_text_plugins: ^1.0.8
  speech_to_text: ^4.2.1
  hand_signature: ^2.0.0
  koukicons: ^2.0.3
  flutter_tts: ^3.1.0
  translator: ^0.1.7
  learning_translate: ^0.0.3+1
  learning_input_image: ^0.0.5
  provider: ^5.0.0
  geolocator: ^7.2.0+1
  google_maps_flutter: ^2.0.6
  dio: ^4.0.0
  highlight_text: ^1.0.0
  avatar_glow: ^2.0.1
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.9
#  audioplayers: ^0.19.1














  emoji_picker: ^0.1.0
  intl: ^0.17.0
  flutter_keyboard_visibility: ^5.0.2
  socket_io_client: ^1.0.1
  web_socket_channel: ^1.0.15
  multi_select_item: ^1.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:

  uses-material-design: true


  assets:
    - images/

